logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security=DEBUG:

  file:
    path: logs/storage.log

spring:
  datasource:
    password:
    url:
    username:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true


server:
  root: "C:/storage/"