logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security=DEBUG:

  file:
    path: logs/PhoeStorage.log

spring:
  datasource:
    password: "%Wh@BJrX8z3uHugD7JPG#%"
    url: jdbc:mysql://188.228.52.113/phoestorage
    username: storage

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true


server:
  root: "C:/PhoeStorage/"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  metrics:
    distribution:
      percentiles:
        dir.browse.controller: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        dir.browse.controller: true
