logging:
  level:
    root: info
    org:
      hibernate.SQL: error
      springframework:
        security=DEBUG:

  file:
    path: logs/storage.log

spring:
  datasource:
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true

server:
  root: ${APP_ROOT}