/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_phoestorage_zip_ZipBridge */

#ifndef _Included_server_phoestorage_zip_ZipBridge
#define _Included_server_phoestorage_zip_ZipBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_phoestorage_zip_ZipBridge
 * Method:    streamZip
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_server_phoestorage_zip_ZipBridge_streamZip
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
